title: Dylan Paulus
email: dylantpaulus@gmail.com
description: >
  Fullstack programmer working on the web
baseurl: ""
url: "http://dylanpaulus.com"
twitter_username: dtpaulus
github_username:  ganderzz

permalink: pretty

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: dp
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
