title: Dylan Paulus
email: dylantpaulus@gmail.com
description: >
  Programmer
baseurl: ""
url: ""
twitter_username: dtpaulus
github_username:  ganderzz

permalink: pretty

markdown: kramdown
theme: dp
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
