title: Dylan Paulus
email: dylantpaulus@gmail.com
description: >
  Fullstack programmer working on the web
baseurl: ""
url: "http://dylanpaulus.com"

author:
  twitter: "DylanPaulus"
  github: "ganderzz"
  linkedin: "dylanpaulus"
  stackoverflow: "7828585/dpaulus"

permalink: pretty

defaults:
  - scope:
      path: "images"
    values:
      image: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 5

theme: dp
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
