backend:
  name: git-gateway
  branch: master
  repo: https://github.com/ganderzz/ganderzz.github.io

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matte
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Is Published", name: "published", widget: "boolean" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Credits", name: "image_credit", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
